/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektas.gui;

import java.awt.Choice;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.InputMismatchException;
import java.util.Locale;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Competitors.Competitor;
import Competitors.YoungerCompetitor;
import java.nio.charset.Charset;

/**
 *
 * @author User
 */
public class DataAddForm extends javax.swing.JFrame {
    
    private final int maxGroups = 10;
    //"Vyrai", "Moterys", "Jauniai", "Jaunės", "Jaunučiai", "Jaunutės", "Berniukai", "Mergaitės", "Vaikai berniukai", "Vaikai mergaitės"
    public Group[] ageGroups = new Group[maxGroups];
    private String fileFormat = ".txt";
    private File file;
    private final int year = Calendar.getInstance().get(Calendar.YEAR);
    private Choice[] choiceArray;
    private final String[] groupNames = {"Vyrai", "Moterys", "Jauniai", "Jaunės", "Jaunučiai", "Jaunutės", "Berniukai", "Mergaitės", "Vaikai berniukai", "Vaikai mergaitės"};
    public ArrayList<YoungerCompetitor> Competitors = new ArrayList<YoungerCompetitor>();
    private int[] chosenYear;
    
    /**
     * Creates new form DataAddForm
     */
    public DataAddForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        textArea2 = new java.awt.TextArea();
        toCompetitionFormBtn = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        moterysNuo = new java.awt.Choice();
        jaunesNuo = new java.awt.Choice();
        jaunutesNuo = new java.awt.Choice();
        mergaitesNuo = new java.awt.Choice();
        vyraiIki = new java.awt.Choice();
        jaunuciaiIki = new java.awt.Choice();
        berniukaiIki = new java.awt.Choice();
        moterysIki = new java.awt.Choice();
        jauniaiIki = new java.awt.Choice();
        jaunesIki = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        jaunutesIki = new java.awt.Choice();
        jLabel7 = new javax.swing.JLabel();
        mergaitesIki = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vyraiNuo = new java.awt.Choice();
        jauniaiNuo = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jaunuciaiNuo = new java.awt.Choice();
        berniukaiNuo = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();
        vaikaiNuo = new java.awt.Choice();
        vaikaiIki = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        vaikaiMergaitesNuo = new java.awt.Choice();
        vaikaiMergaitesIki = new java.awt.Choice();
        setAgeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Dalyvių sąrašas .txt formatu");

        jButton2.setText("Įkelti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textArea2.setEditable(false);
        textArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        toCompetitionFormBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toCompetitionFormBtn.setEnabled(false);
        toCompetitionFormBtn.setLabel("Eiti į rungčių priskyrimą");
        toCompetitionFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCompetitionFormBtnActionPerformed(evt);
            }
        });

        moterysNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        jaunesNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        jaunutesNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        mergaitesNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        jaunuciaiIki.setPreferredSize(new java.awt.Dimension(62, 20));

        berniukaiIki.setPreferredSize(new java.awt.Dimension(62, 20));

        moterysIki.setPreferredSize(new java.awt.Dimension(62, 20));

        jauniaiIki.setPreferredSize(new java.awt.Dimension(62, 20));

        jaunesIki.setPreferredSize(new java.awt.Dimension(62, 20));

        jLabel6.setText("Berniukai");

        jaunutesIki.setPreferredSize(new java.awt.Dimension(62, 20));

        jLabel7.setText("Moterys");

        mergaitesIki.setPreferredSize(new java.awt.Dimension(62, 20));

        jLabel8.setText("Jaunės");

        jLabel9.setText("Jaunutės");

        jLabel10.setText("Mergaitės");

        jLabel11.setText("Metai nuo:");

        jLabel12.setText("Metai iki:");

        jauniaiNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        jLabel1.setText("Parinkti grupes");

        jLabel3.setText("Vyrai");

        jLabel4.setText("Jauniai");

        jLabel5.setText("Jaunučiai");

        jaunuciaiNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        berniukaiNuo.setPreferredSize(new java.awt.Dimension(62, 20));

        jLabel13.setText("Vaikai berniukai");

        jLabel14.setText("Vaikai mergaitės");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vyraiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyraiIki, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jauniaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jauniaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jaunuciaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jaunuciaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(berniukaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(berniukaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vaikaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vaikaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel13))))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moterysIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moterysNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jaunesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jaunutesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunutesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(mergaitesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mergaitesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vaikaiMergaitesNuo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vaikaiMergaitesIki, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(vyraiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jauniaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunuciaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(berniukaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moterysNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunutesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mergaitesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaikaiNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaikaiMergaitesNuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mergaitesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunutesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moterysIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(berniukaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaunuciaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(vyraiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jauniaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaikaiIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaikaiMergaitesIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setAgeBtn.setText("Patvirtinti");
        setAgeBtn.setEnabled(false);
        setAgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAgeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 990, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(setAgeBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(toCompetitionFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(toCompetitionFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(setAgeBtn)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            try {
                getData();
            } catch (FileNotFoundException ex) {
                System.out.println("Nerastas failas");
            } catch (IOException ex) {
                Logger.getLogger(DataAddForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        addChoice();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void toCompetitionFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCompetitionFormBtnActionPerformed
          closeTheCurrentFrameAndOpenNew(evt);
    }//GEN-LAST:event_toCompetitionFormBtnActionPerformed

    private void setAgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAgeBtnActionPerformed
        getChoices();
        toCompetitionFormBtn.setEnabled(true);
    }//GEN-LAST:event_setAgeBtnActionPerformed

    private void closeTheCurrentFrameAndOpenNew(java.awt.event.ActionEvent evt)
    {
        dispose();//To close the current window
        
        ResultsForm resultsForm = new ResultsForm();
        resultsForm.setAgeGroups(ageGroups);
        resultsForm.setCompetitors(Competitors);
        resultsForm.setVisible(true);
       /* MainForm closeCurrentWindow = new MainForm();
        closeCurrentWindow.setVisible(true);*/
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataAddForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice berniukaiIki;
    private java.awt.Choice berniukaiNuo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Choice jaunesIki;
    private java.awt.Choice jaunesNuo;
    private java.awt.Choice jauniaiIki;
    private java.awt.Choice jauniaiNuo;
    private java.awt.Choice jaunuciaiIki;
    private java.awt.Choice jaunuciaiNuo;
    private java.awt.Choice jaunutesIki;
    private java.awt.Choice jaunutesNuo;
    private java.awt.Choice mergaitesIki;
    private java.awt.Choice mergaitesNuo;
    private java.awt.Choice moterysIki;
    private java.awt.Choice moterysNuo;
    private javax.swing.JButton setAgeBtn;
    private java.awt.TextArea textArea2;
    private java.awt.Button toCompetitionFormBtn;
    private java.awt.Choice vaikaiIki;
    private java.awt.Choice vaikaiMergaitesIki;
    private java.awt.Choice vaikaiMergaitesNuo;
    private java.awt.Choice vaikaiNuo;
    private java.awt.Choice vyraiIki;
    private java.awt.Choice vyraiNuo;
    // End of variables declaration//GEN-END:variables
    
    public void setUploadLock()
    {
        addChoice();
    }
    
    public void getLoadData()
    {
        File file = new File("save.txt");
        
        getData(file);
    }
    
    private boolean getData(File file)
    {
        String line;
        try {
            FileReader fileReader = 
                new FileReader(file.getAbsolutePath());

            BufferedReader bufferedReader = 
                new BufferedReader(fileReader);
            
            while((line = bufferedReader.readLine()) != null) 
            {
                YoungerCompetitor temp = new YoungerCompetitor();
                if(line != null)
                {
                    temp.parse(line);
                }
                if(temp.validate() == "" && !Competitors.contains(temp))
                { 
                    Competitors.add(temp);
                }
            }  
            Competitors.sort(Competitor.sortByID);
            //uždarome skaitymą
            bufferedReader.close(); 
            //išvedame gautus duomenis
            printData();
            //perduodame i pagr klase
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                file.getAbsolutePath() + "'"); 
            return false;
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + file.getAbsolutePath() + "'");  
            return false;
        }
        setAgeBtn.setEnabled(true);
        return true;
    }
    
    /*
    nuskaito pasirinktą tekstinį failą paspaudus įkėlimo mygtuką
    */
    private boolean getData() throws FileNotFoundException, IOException
    {
        String line = "";
        try {
            FileReader fileReader = 
                new FileReader(file.getAbsolutePath());

            BufferedReader bufferedReader = new BufferedReader(
                new InputStreamReader(new FileInputStream(file),"UTF-8"));
               // new BufferedReader(fileReader);
            
            while((line = bufferedReader.readLine()) != null) 
            {
                YoungerCompetitor temp = new YoungerCompetitor();
                if(line != null)
                {
                    temp.parse(line);
                }
                if(temp.validate() == "" && !Competitors.contains(temp))
                { 
                    Competitors.add(temp);
                }
            }  
            Competitors.sort(Competitor.sortByID);
            //uždarome skaitymą
            bufferedReader.close(); 
            //išvedame gautus duomenis
            printData();
            //perduodame i pagr klase
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                file.getAbsolutePath() + "'"); 
            return false;
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + file.getAbsolutePath() + "'");  
            return false;
        }
        catch(Exception ex) {
              
            return false;
        }
        setAgeBtn.setEnabled(true);
        return true;
    }
    
        private void setChoices()
    {
        choiceArray = new Choice[20];
        choiceArray[0] = vyraiNuo;
        choiceArray[1] = vyraiIki;
        choiceArray[2] = moterysNuo;
        choiceArray[3] = moterysIki;
        choiceArray[4] = jauniaiNuo;
        choiceArray[5] = jauniaiIki;
        choiceArray[6] = jaunesNuo;
        choiceArray[7] = jaunesIki;
        choiceArray[8] = jaunuciaiNuo;
        choiceArray[9] = jaunuciaiIki;
        choiceArray[10] = jaunutesNuo;
        choiceArray[11] = jaunutesIki;
        choiceArray[12] = berniukaiNuo;
        choiceArray[13] = berniukaiIki;
        choiceArray[14] = mergaitesNuo;
        choiceArray[15] = mergaitesIki;
        choiceArray[16] = vaikaiNuo;
        choiceArray[17] = vaikaiIki;
        choiceArray[18] = vaikaiMergaitesNuo;
        choiceArray[19] = vaikaiMergaitesIki;
    }
    
    /*
    prideda metų pasirinkimą nuo 1970 iki dabartinių
    reikalinga užtikrinti amžių grupių teisingam įvedimui
    */
    private void addChoice()
    {
        setChoices();
        for(Choice c: choiceArray)
        {
            if(c.getItemCount() == 0)
            {
                for(int i=1970;i<=year;i++)
                {
                    c.add(Integer.toString(i));
                }
            }
        }
    }
    
    private void getChoices()
    {
        int index = 0;
        chosenYear = new int[maxGroups];
        for(int i=0;i<maxGroups;i++)
        {
            System.out.println(groupNames[i] + choiceArray[index].getSelectedItem().toString() + choiceArray[index+1].getSelectedItem());
            ageGroups[i] = new Group(groupNames[i], Integer.parseInt(choiceArray[index].getSelectedItem().toString()), Integer.parseInt(choiceArray[index+1].getSelectedItem()));
            index += 2;
        }
    }
    
    /*
    išvedimas į textArea
    */
    private void printData()
    {
        String outputText = "";
        Competitors.sort(YoungerCompetitor.sortByID);
        outputText += "viso " + Competitors.size() + "\n";
        for(YoungerCompetitor c: Competitors)
        {
            outputText += c.toString() + "\n";
        }
        textArea2.setText(outputText);
    }
}
